### ISSUE TITLE
str object has no attribute 'send_keys'

### ISSUE THREAD

**Issue by ankushblue** [yasharmaster/Flipkart-Review-Scraper#1]
Hi,

I tried your code exactly as you mentioned and I found the following issue when i run it

File "scrape.py", line 40, in <module>
button.send_keys(Keys.RETURN) AttributeError: 'str' object has no attribute 'send_keys'

I have used the same url as the one that you have used in your code.

Can you please help debug this issue?

**Comment by yasharmaster** [comment]
@ankushblue I'll look into it and will update the code accordingly.

**Comment by yasharmaster** [comment]
@ankushblue I did not get this error message when I ran the script today. Instead, there was a problem in finding Upvotes and Downvotes, which I have fixed now. So the script is working fine on my system and you can see the reviews scraped stored in the `review.txt` file.

**Comment by yasharmaster** [comment]
@ankushblue I'm closing this issue. You can reopen if you need further assistance.
