### ISSUE TITLE
Flipkart - Unauthorized Repository Removal Request

### ISSUE THREAD

**Issue by Cybersecurity-Specialist** [yasharmaster/Flipkart-Review-Scraper#3]
Hi,

My name is Caleb, a Security Analyst from iZOOlogic Ltd that works on behalf of our client Flipkart.

Our client noticed this repository and has reported to us that they do not authorize nor have an affiliation with you to use their name.

We ask that you delete or remove anything related to our client on this repository as this is not authorized and clearly violated the trademark rights of Flipkart. To avoid any legal action, please remove it immediately.

Regards,

Caleb Stark
Security Analyst

**Comment by yasharmaster** [comment]
Hey @iZOOlabs-GSOC , I have removed all the references to said company as requested. Everything else that is there in the repo is already in public domain. Please reopen this issue in case there is anything else I can help you with.

**Comment by Cybersecurity-Specialist** [comment]
Greetings,

Our client is not satisfied with the changes, we request that you remove the term "Flipkart" as well as the demo showing the Flipkart logo and website. We advise you to change this to something else or another company as long as it does not involve Flipkart.

We are hoping for your quick response.

Regards,
Jorge Liz
