### ISSUE TITLE
Flipkart - Unauthorized Content Removal Request

### ISSUE THREAD

**Issue by Cybersecurity-Specialist** [yasharmaster/Flipkart-Review-Scraper#4]
Greetings,

My name is Jorge Liz from iZOOlogic. I am an authorized representative of Flipkart
[Flipkart Brand Authorization.pdf](https://github.com/yasharmaster/Fk-Review-Scraper/files/5690708/Flipkart.Brand.Authorization.pdf)
. 

Our client is not satisfied with the changes, we request that you remove the term "Flipkart" as well as the demo showing the Flipkart logo and website. We advise you to change this to something else or another company as long as it does not involve Flipkart.

We are hoping for your quick response.

Regards,
Jorge Liz

**Comment by yasharmaster** [comment]
Hi, I have removed the demo. There is no reference to flipkart in the repository. Please reopen the issue in case you need help with something else.
